[package]
name = "tg-rusty-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
html_parser = "0.7.0"
log = "0.4.22"
reqwest = {version = "0.12.7", features = ["json"]}
tokio = { version = "1.40.0", features = ["full"] }
